import os
import glob
import pandas as pd
import json

RESULTS_DIR = 'results'
REPORT_PATH = os.path.join(RESULTS_DIR, 'FINAL_REPORT.md')

def load_system_info():
    # Try to extract system info from the first available JSON
    json_files = glob.glob(os.path.join(RESULTS_DIR, '*.json'))
    if not json_files:
        return {}
    
    with open(json_files[0], 'r') as f:
        data = json.load(f)
        return data.get('system', {})

def get_markdown_table(csv_path):
    if not os.path.exists(csv_path):
        return "_No data available._"
    
    df = pd.read_csv(csv_path)
    
    # Format numeric columns
    for col in df.columns:
        if df[col].dtype == 'float64':
            df[col] = df[col].round(2)
            
    return df.to_markdown(index=False)

def generate_report():
    sys_info = load_system_info()
    
    with open(REPORT_PATH, 'w') as f:
        f.write("# PQC Benchmark Suite for XenevaOS — Final Report\n\n")
        
        f.write("## System Information\n")
        f.write(f"- **Compiler:** {sys_info.get('compiler', 'N/A')}\n")
        f.write(f"- **OpenSSL:** {sys_info.get('openssl', 'N/A')}\n")
        f.write(f"- **CPU:** {sys_info.get('cpu', 'N/A')}\n")
        f.write(f"- **Kernel:** {sys_info.get('kernel', 'N/A')}\n")
        f.write(f"- **RAM:** {sys_info.get('ram', 'N/A')}\n\n")
        
        f.write("## Experiment 1: ECDH P-256 vs ML-KEM-768\n")
        f.write("Key establishment benchmarking comparing classical Elliptic Curve Diffie-Hellman with Post-Quantum ML-KEM.\n\n")
        f.write(get_markdown_table(os.path.join(RESULTS_DIR, 'ecdh_vs_mlkem_results.csv')) + "\n\n")
        f.write("![Plots](plots/exp1_ecdh_vs_mlkem.png)\n\n")
        
        f.write("## Experiment 2: RSA-2048 vs ML-DSA-65\n")
        f.write("Digital signature benchmarking comparing classical RSA with Post-Quantum ML-DSA.\n\n")
        f.write(get_markdown_table(os.path.join(RESULTS_DIR, 'rsa_vs_mldsa_results.csv')) + "\n\n")
        f.write("![Plots](plots/exp2_rsa_vs_mldsa.png)\n\n")
        
        f.write("## Experiment 3: Secure Boot Simulation\n")
        f.write("Simulating verification latency during kernel boot for a 4MB payload.\n\n")
        f.write(get_markdown_table(os.path.join(RESULTS_DIR, 'secure_boot_results.csv')) + "\n\n")
        f.write("![Plots](plots/exp3_secure_boot.png)\n\n")
        
        f.write("## Experiment 4: Package Verification\n")
        f.write("Simulating software supply chain batch verification (100, 500, 1000 packages of 1MB each).\n\n")
        f.write(get_markdown_table(os.path.join(RESULTS_DIR, 'package_verify_results.csv')) + "\n\n")
        f.write("![Plots](plots/exp4_package_verify.png)\n\n")
        
        f.write("## Experiment 5: Secure IPC Simulation\n")
        f.write("Simulating round-trip secure message passing (Keygen -> KDF -> AES Encrypt/Decrypt) on a 4KB payload.\n\n")
        f.write(get_markdown_table(os.path.join(RESULTS_DIR, 'secure_ipc_results.csv')) + "\n\n")
        f.write("![Plots](plots/exp5_secure_ipc.png)\n\n")
        
        f.write("---\n*Report automatically generated by Stage 2 Python Analysis Pipeline.*\n")
        
    print(f"Report generated at {REPORT_PATH}")

if __name__ == "__main__":
    print("Generating Markdown report...")
    generate_report()
